FROM node:16-alpine AS BUILD_IMAGE

RUN apk update && apk add bash curl && rm -rf /var/cache/apk/*

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

# install package-lock.json dependencies
RUN npm ci

COPY . .
COPY .env.development .env.production
COPY .env.development .env

# build application
RUN npm run build

FROM node:16-alpine

WORKDIR /usr/src/app

# copy from build image
COPY --from=BUILD_IMAGE /usr/src/app ./

EXPOSE 3010

CMD [ "npm", "start" ]
