apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atcampus-notetaking-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = '{{ .Values.host }}' ) {
        rewrite ^ https://www.{{ .Values.host }}$request_uri permanent;
      }
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"

spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atcampus-notetaking-frontend-service
                port:
                  number: {{ .Values.port }}
    - host: www.{{.Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atcampus-notetaking-frontend-service
                port:
                  number: {{ .Values.port }}

  tls:
    - hosts:
        - {{.Values.host }}
        - www.{{.Values.host }}
      secretName: notetaking-frontend-tls
