kind: Service
apiVersion: v1
metadata:
  name: atcampus-notetaking-frontend-service
spec:
  selector:
    app: atcampus-notetaking-frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
